name:                traycer-hs
version:             0.3.1
github:              5hubh4m/traycer-hs
license:             MIT
author:              Shubham Chaudhary
maintainer:          shubhamchaudhary1996@gmail.com
copyright:           © 2017, Shubham Chaudhary

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A ray-tracing library in pure Haskell.
category:            geometry, graphics, ray-tracing, rendering
description:         Please see the README on Github at <https://github.com/5hubh4m/traycer-hs#readme>

dependencies:
- aeson
- vector
- base
- bytestring
- time
- array
- lens
- repa
- JuicyPixels
- yaml
- linear
- random

library:
  source-dirs: src

executables:
  traycer-hs:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Odph
    - -rtsopts
    - -threaded
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    - -funbox-strict-fields
    - -fllvm
    - -optlo-O3
    dependencies:
    - traycer-hs
